#服务启动端口号
server:
  port: 8300
#服务名称(注册到eureka名称)
spring:
  application:
    name: app-qtatelier-member
#服务注册到eureka地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8100/eureka
#swagger相关配置,推荐配置文件配置
#swagger:
#  base-package: com.qtatelier.member.service
#  title: 威爷的商城
#  description: 项目基于SpringCloud2.x进行构建
#  version: 1.1
#  terms-of-service-url: www.qtatelier.com
#  contact:
#    name: 夏威伟
#    email: 1104841692@qq.com
